luabase/definite-chartlib

src/types/option.ts
=> feat: add initial version of chart option schema

src/chart.ts, test/unit/chart.test.ts
=> fix: make metric and dim mutations atomic

src/determine/axis.ts
=> fix: add max value to interval #33

.vscode/settings.json, README.md, src/chart.ts, src/determine/axis.ts, src/determine/calendar.ts, src/determine/datasets.ts, src/determine/grid.ts, src/determine/legend.ts, src/determine/series.ts, src/determine/title.ts, src/determine/toolbox.ts, src/determine/tooltip.ts, src/determine/visualMap.ts, src/factory.ts, src/main.ts, test/charts/bar.test.ts, test/charts/line.test.ts, test/unit/chart.test.ts, test/unit/conversion.test.ts
Allows metrics for bar and line charts to be plotted on either a left or right axis
=> feat: fully implement multiple axes support

src/chart.ts, src/factory.ts, test/unit/chart.test.ts
Adds a `.equals()` method to the chart class
=> feat: add equality comparator to chart class

.devcontainer/devcontainer.json, .github/workflows/test.yml, src/determine/tooltip.ts, src/types/echarts/tooltip.ts, test/charts/bar.test.ts, test/charts/calendar.test.ts, test/charts/combo.test.ts, test/charts/heatmap.test.ts, test/charts/line.test.ts, test/charts/pie.test.ts, test/charts/scatter.test.ts
Background = `bg-zinc-900`
Text = `text-zinc-300`
=> feat: tooltip should use brand colors

.github/workflows/pr.yml, dist/index.cjs, dist/index.js, http/package.json, package.json, src/determine/axis.ts, src/determine/series.ts, src/formatters.ts, test/charts/combo.test.ts, test/charts/kpi.test.ts
- chore: bump version
- fix: use proper formatter for multi-axis charts
- fix: use differet formatters for KPI chart
=> fix: formatters for multi-axis and KPI charts

dist/index.cjs, dist/index.d.ts, dist/index.js, http/package.json, package.json, src/chart.ts
If dimension passed is null or undefined, add a default
=> default dimension

dist/index.cjs, dist/index.d.ts, dist/index.js, http/package.json, package.json, src/chart.ts, src/determine/axis.ts, src/determine/series.ts, src/types/literals.ts
=> funnel charts

.github/CODEOWNERS, dist/index.cjs, dist/index.d.ts, dist/index.js, http/package.json, package.json, src/determine/axis.ts, src/determine/legend.ts, src/determine/tooltip.ts, src/formatters.ts, src/types/echarts/tooltip.ts
=> add formatters

dist/index.cjs, dist/index.d.ts, dist/index.js, http/package.json, package.json, src/constants/color.ts, src/determine/axis.ts, src/determine/calendar.ts, src/determine/grid.ts, src/determine/legend.ts, src/determine/series.ts, src/determine/tooltip.ts, src/formatters.ts
- formats long values on axis
- improves margins
- replaces old colors (zinc) with new DS colors
=> improve margins, new ds colors, add formatting to values on axis

dist/index.cjs, dist/index.js, http/package.json, package.json, src/factory.ts
=> add kpi to shuffle

dist/index.cjs, dist/index.d.ts, dist/index.js, http/package.json, package.json, src/chart.ts, src/determine/axis.ts, src/determine/grid.ts, src/determine/legend.ts, src/determine/title.ts
=> show legend title

dist/index.cjs, dist/index.js, http/package.json, package.json, src/determine/axis.ts, src/determine/datasets.ts, src/determine/tooltip.ts
=> make stacked bars full height and show percentage values

dist/index.cjs, dist/index.d.ts, dist/index.js, http/index.js, http/package.json, package.json, src/chart.ts, src/factory.ts, src/formatters.ts, src/types/legacy.ts, src/types/literals.ts, src/types/option.ts
=> Add meta to chart

dist/index.cjs, dist/index.d.ts, dist/index.js, http/index.js, http/package.json, package.json, src/determine/axis.ts, src/factory.ts, src/main.ts
=> make tables w many rows default to bar

dist/index.cjs, dist/index.js, http/package.json, package.json, src/determine/axis.ts, src/factory.ts
fixes shuffle. heatmap and scatter used to break sometimes
=> Fix shuffle for bad chart configs

dist/index.cjs, dist/index.js, http/package.json, package.json, src/factory.ts, src/main.ts
=> fix kpi generation

README.md, dist/index.cjs, dist/index.d.ts, dist/index.js, http/package.json, package.json, schema.json, src/chart.ts, src/determine/datasets.ts, src/determine/series.ts, src/determine/tooltip.ts, src/factory.ts, src/types/literals.ts
=> sankey chart type

dist/index.cjs, dist/index.d.ts, dist/index.js, http/package.json, package.json, src/chart.ts, src/determine/axis.ts, src/types/option.ts
=> show all axis labels

dist/index.cjs, dist/index.js, http/package.json, package.json, src/determine/series.ts, src/determine/tooltip.ts
=> format pie

dist/index.cjs, dist/index.js, http/package.json, package.json, src/determine/visualMap.ts
=> fix heatmap

dist/index.cjs, dist/index.d.ts, dist/index.js, http/package.json, package.json, src/chart.ts, src/constants/color.ts, src/constants/gradients.ts, src/constants/index.ts, src/constants/palette.ts, src/determine/visualMap.ts, src/types/literals.ts, src/types/option.ts
=> color palette

dist/index.cjs, dist/index.d.ts, dist/index.js, http/package.json, package.json, src/chart.ts, src/determine/series.ts, src/determine/tooltip.ts, src/determine/visualMap.ts, src/types/option.ts
=> heatmap improvements
